apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-pvc
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi   

# AKS already provisioned Storage classes managed-premium and default as part of 
# default cluster setup      