apiVersion: v1
kind: Service
metadata:
  name: usermgmt-webapp-service
  namespace: argocd
  labels:
    app: usermgmt-webapp
spec:
  type: LoadBalancer
  selector:
    app: usermgmt-webapp
  ports:
    - port: 80
      targetPort: 8080
