apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-db-password
  namespace: argocd
spec:
  encryptedData:
    db-password: AgB7h4r5VG4CO9BKr61YvwqiYYQVTc85O+qOg1lBzTBXwrEnunF/Ld0E0NV0R7RXia08Pn6y4gPX0SjSUwUjv1K7j6UzI7uL3x/4zt0NU5QvCefcZT18CnbB0hYMxhk5T8JIRu/A71mxmotiGzDULFe1IE2/HyrbqIbJFXt6Y391VF1MNwLiEX62Wo9zEzd1Q+zoFOqENvBtxsj9d+PiSobtUfJQ3XHJSLnrRKSKSZrG5OLPK9vYl8aGgH7kNZSVp6QS8kIvcCQ3pSnU1rE88D1tzKtbY2v4NFvUiNcPH3HYCLu+/hIF6P0BAyvaVotB7L6YTYOE/zCuOD57VvYx2sKIJ24LaFKI7n9jqwWaV/9FmwJrN+6dY9kKzKEK9lvsFyx/XNGD3wsq1+y6xrOxyxaforu0moEOp+JlqBI5FETNE7nUHEznyVAw3fghQ0Doa/LbSuYCI3r5J7hxo6riYyRzBl6PJGbgOK3NW1+MNV3kkS5YwcN2RsSOnku5vrI3mvG/qhOKoZNU5HNyV36ZsbWCPDWnKRoV0grW7bq19Q+62LPVhqTCanzWAPHrGNceyYpqh1bppXVeOoOu6hTsKvVaNUXdFhJIiYMy8M0kgo99nsRIaRtmBDQ4aq5/pdSKovXNK+uUGCCM7DoGD1jck0y7vWtysmvmph3zNQzc+giB/V3mQS8SkixumRSNgHsEyEjtVT4v+LTZiisiXrM=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-db-password
      namespace: argocd
    type: Opaque

