name: 2-actions-ci-cd-aks-tf

on:
  push:
    branches: [ main ]
    paths: .github/workflows/2-actions-ci-cd-aks-tf.yml
  pull_request:
    branches: none
  workflow_dispatch:

jobs:

  build-deploy-aks:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: acrforakstf023.azurecr.io
      IMAGE_NAME: web-app
      IMAGE_TAG: ${{ github.run_number }}
      AKS_RESOURCE_GROUP: rg-aks-cluster-tf-023
      AKS_NAME: aks-cluster
      TERRAFORM_VERSION: 1.1.9
      WORKING_DIRECTORY: infra

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:

    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Container Registry Login
      run: |
        az acr login --name acrforakstf023

    - name: Build Docker Image
      working-directory: .
      run: |
        docker build ./MvcApp/ \
          --file ./MvcApp/Dockerfile \
          --tag $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG \
          --no-cache

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        image-ref: '${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'MEDIUM,HIGH,CRITICAL'

    - name: Push Image to ACR
      run: |
        docker push $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG
